apps/alumnos_mesas_examen/urls.py
# -*- coding: utf-8 -*-
from django.urls import include, path
from rest_framework import routers

from .views import (
	RegistroMesaExamenViewSet,
	AlumnoMesaExamenView,
	AlumnoMesaExamenCreate,
	AlumnoMesaExamenDetail,
	AlumnoMesaExamenDelete,
	AlumnoMesaExamenUpdate,
)

app_name = 'alumnos_mesas'

router = routers.DefaultRouter()
router.register('api', RegistroMesaExamenViewSet)

urlpatterns = [
	path('', include(router.urls)),
	path('listado_alumnos/', AlumnoMesaExamenView.as_view(), name='listado_alumnos'),
	path('formulario_registro/', AlumnoMesaExamenCreate.as_view(), name='formulario_alumno'),
	path('detalle_alumno/<int:pk>/', AlumnoMesaExamenDetail.as_view(), name='detalle_alumno'),
	path('borrar_alumno/<int:pk>/', AlumnoMesaExamenDelete.as_view(), name='borrar_alumno'),
	path('modificar_alumno/<int:pk>/', AlumnoMesaExamenUpdate.as_view(), name='modificar_alumno'),
]

apps/materia/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import (
MateriaViewSet, MateriaView,
MateriaDetail, MateriaCreate,
MateriaUpdate, MateriaDelete
)


app_name = 'materia'

router = routers.DefaultRouter()
router.register('api', MateriaViewSet)


urlpatterns = [
	path ('', include(router.urls)),
	path ('listado/', MateriaView.as_view(), name='listado'),
	path ('detalle/<int:pk>/', MateriaDetail.as_view(), name='detalle'),
	path ('crear/', MateriaCreate.as_view(), name='crear'),
	path ('modificar/<int:pk>/', MateriaUpdate.as_view(), name='modificar'),
	path ('borrar/<int:id>/', MateriaDelete.as_view(), name='borrar'),
]

secretaria/urls.py
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import path, include
from apps.core.views import GeneralView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('materia/', include('apps.materia.urls')),
    path('registro_mesa_examen/', include('apps.alumnos_mesas_examen.urls')),
    path('', GeneralView.as_view(), name='general'),
    path('accounts/', include('django.contrib.auth.urls')),
]

apps/alumnos_mesas_examen/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from apps.materia.models import Materia

class RegistroMesaExamen(models.Model):
	nombre = models.CharField(max_length=40, help_text='Ingrese el nombre del alumno')
	apellido = models.CharField(max_length=40, help_text='Ingrese el apellido del alumno')
	dni = models.PositiveIntegerField(
		help_text='Ingrese el dni del alumno',
		validators=[
			MaxValueValidator(999999999),
			MinValueValidator(1000000)
		]
	)
	materia = models.ForeignKey(Materia, on_delete=models.CASCADE, help_text='Ingrese un materia a rendir') #Hay que hacer un ForeignKey (esperar a nahuel que suba sus cambios)
	correo_electronico = models.CharField(max_length=100, help_text='Ingrese un correo electronico para poder comunicarnos con el alumno')

	class Meta:
		verbose_name='registro para mesa de examen'
		verbose_name_plural='registros para mesas de examenes'

	def __str__(self):
		return '%s %s %s' % (self.nombre, self.apellido, self.materia)

apps/core/models.py
from django.db import models

# Create your models here.

apps/materia/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Materia(models.Model):

	nombre = models.CharField(
		max_length=50,
		help_text='Ingrese el nombre de la materia.'
	)

	año = models.PositiveSmallIntegerField(
		validators=[
			MaxValueValidator(6),
			MinValueValidator(1)
		],
		help_text='Ingrese el año de la materia.'
	)

	fecha_hora = models.DateTimeField(
		'Fecha y Hora',
		help_text='Ingrese la fecha y hora a la que se rinde la materia. Formato: "DD/MM/AAAA HH:MM"'
	)

	aula = models.CharField(
		max_length=50,
		help_text='Ingrese el aula en la que se rinde la materia.'
	)

	profesores = models.CharField(
		max_length=150,
		help_text='Ingrese los profesores que evaluarán. Formato: "Nombre Apellido, Nombre Apellido, etc."'
	)

	class Meta:
		verbose_name='Materia'
		verbose_name_plural='Materias'

	def __str__(self):
		return '%s %sº' % (self.nombre, self.año)

apps/alumnos_mesas_examen/views.py
# -*- coding: utf-8 -*-
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissions
from django.contrib.auth.mixins import LoginRequiredMixin
from .serializers import RegistroMesaExamenSerializer
from .models import RegistroMesaExamen
from django.shortcuts import get_object_or_404


class RegistroMesaExamenViewSet(viewsets.ModelViewSet):
	queryset = RegistroMesaExamen.objects.all()
	serializer_class = RegistroMesaExamenSerializer
	permission_classes = [DjangoModelPermissions]

class AlumnoMesaExamenView(LoginRequiredMixin, ListView):
	model = RegistroMesaExamen
	template_name = 'alumnos_mesas_examen/listado_alumnos.html'
	context_object_name = 'alumnos_registrados'

class AlumnoMesaExamenCreate(CreateView):
	model = RegistroMesaExamen
	fields= ['nombre', 'apellido', 'dni', 'materia', 'correo_electronico']
	template_name = 'alumnos_mesas_examen/registrar_alumno.html'
	success_url = reverse_lazy('alumnos_mesas:listado_alumnos')

class AlumnoMesaExamenDetail(LoginRequiredMixin, DetailView):
	model = RegistroMesaExamen
	template_name = 'alumnos_mesas_examen/detalle_alumno.html'
	context_object_name = 'alumno_registrado'

class AlumnoMesaExamenDelete(LoginRequiredMixin, DeleteView):
	model = RegistroMesaExamen
	template_name = 'alumnos_mesas_examen/borrar_alumno.html'
	success_url = reverse_lazy('alumnos_mesas:listado_alumnos')
	context_object_name = 'alumno_registrado'

class AlumnoMesaExamenUpdate(LoginRequiredMixin, UpdateView):
	model = RegistroMesaExamen
	fields = ['nombre', 'apellido', 'dni', 'materia', 'correo_electronico']
	template_name = 'alumnos_mesas_examen/modificar_alumno.html'
	success_url = reverse_lazy('alumnos_mesas:listado_alumnos')
	context_object_name = 'alumno_registrado'

apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class GeneralView(TemplateView):
	template_name = 'general.html'

apps/materia/views.py
# -*- coding: utf-8 -*-


from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissions
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.views.generic.edit import CreateView,UpdateView, DeleteView
from .models import Materia
from .serializers import MateriaSerializer


class MateriaViewSet(viewsets.ModelViewSet):

	queryset = Materia.objects.all()
	serializer_class = MateriaSerializer
	permission_classes = [DjangoModelPermissions] 

class MateriaView(LoginRequiredMixin, ListView):
	model = Materia
	template_name = 'materia/listado.html'
	context_object_name = 'materias'

class MateriaDetail(LoginRequiredMixin, DetailView):
	model = Materia
	template_name = 'materia/detalle.html'
	context_object_name = 'materia'

class MateriaCreate(LoginRequiredMixin, CreateView):
	model = Materia
	fields= ['nombre', 'año', 'fecha_hora', 'aula', 'profesores']
	template_name = 'materia/crear.html'
	success_url = reverse_lazy('materia:listado')

class MateriaUpdate(LoginRequiredMixin, UpdateView):
	model = Materia
	fields= ['nombre', 'año', 'fecha_hora', 'aula', 'profesores']
	template_name = 'materia/modificar.html'
	success_url = reverse_lazy('materia:listado')

class MateriaDelete(LoginRequiredMixin, DeleteView):
    template_name = 'materia/borrar.html'
    success_url = reverse_lazy('materia:listado')
    
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Materia, id=id_)

templates/alumnos_mesas_examen/borrar_alumno.html
{% extends 'general.html' %}
{% load bootstrap4 %}
{% block titulo %}Borrar registro de {{ alumno_registrado.nombre|capfirst }} {{ alumno_registrado.apellido|capfirst }}{% endblock titulo %}
{% block contenido %}

	<h1 class="text-white">Borrar el registro del alumno: {{ alumno_registrado.nombre|capfirst }} {{ alumno_registrado.apellido|capfirst }}</h1>
	<a href="{% url 'alumnos_mesas:detalle_alumno' alumno_registrado.id %}" class="btn btn-danger btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Cancelar</a>
	<div class="card text-white bg-dark mb-3" style="padding: 15px">
	<form action="" method="post">
		{% csrf_token %}
			<p>¿Está seguro que quiere borrar a este alumno de la mesa de examen?</p>
		{% buttons %}
    		<button type="submit" class="btn btn-danger">Borrar registro del alumno.</button>
		{% endbuttons %}
	</form>
	</div>

{% endblock contenido %}

templates/alumnos_mesas_examen/detalle_alumno.html
{% extends 'general.html' %}
{% block titulo %} {{ alumno_registrado.nombre }} {{ alumno_registrado.apellido }} {% endblock titulo %}
{% block contenido %}
	<h1 class="text-white">Detalle del alumno:</h1>

	<a href="{% url 'alumnos_mesas:listado_alumnos' %}" class="btn btn-secondary btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Volver</a>
	<a href="{% url 'alumnos_mesas:modificar_alumno' alumno_registrado.id %}" class="btn btn-secondary btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Modificar</a>
	<a href="{% url 'alumnos_mesas:borrar_alumno' alumno_registrado.id %}" class="btn btn-danger btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Borrar</a>


	<div class="card text-white bg-dark mb-3" style="width: 100%;">
		<div class="card-header"><h5 class="card-title">{{ alumno_registrado.nombre|capfirst }} {{ alumno_registrado.apellido|capfirst }}</h5></div>
		<div class="card-body">
			<p class="card-text">DNI: {{ alumno_registrado.dni }}</p>
			<p class="card-text">Materia: {{ alumno_registrado.materia }}</p>
		</div>
		<div class="card-footer">
			<p class="card-text">Correo Electrónico (contacto): {{ alumno_registrado.correo_electronico }}</p>
		</div>
	</div>

{% endblock contenido %}

templates/alumnos_mesas_examen/listado_alumnos.html
{% extends 'general.html' %}
{% block titulo %}Materias{% endblock titulo %}
{% block contenido %}
<div class="container">
	<h1 class="text-white">Todos los alumnos registrados:</h1>
	<a href="{% url 'alumnos_mesas:formulario_alumno' %}"><button type="button" class="btn btn-outline-light btn-lg btn-block">Registrar un alumno</button></a>
	</br>
	<div class="row">

	{% for alumno_registrado in alumnos_registrados %}
	
	<div class="col-sm-6">
	<div class="card text-white bg-dark mb-3" style="width: 100%;">
		<div class="card-header">
			<a href="{% url 'alumnos_mesas:detalle_alumno' alumno_registrado.id %}" style="a:link {color: white}"><h5 class="card-title">{{ alumno_registrado.nombre|capfirst }} {{ alumno_registrado.apellido|capfirst }}</h5></a>
		</div>
		<div class="card-body">
			<p class="card-text">DNI: {{ alumno_registrado.dni }}</p>
			<p class="card-text">Materia: {{ alumno_registrado.materia }}</p>
		</div>
		<div class="card-footer">
			<p class="card-text">Correo Electrónico (contacto): {{ alumno_registrado.correo_electronico }}</p>
		</div>
	</div>
	</div>

	{% endfor %}

	</div>
	<a href="{% url 'general' %}" class="btn btn-danger btn-lg btn-block" role="button">Volver a la página principal</a>
</div>
{% endblock contenido %}

templates/alumnos_mesas_examen/modificar_alumno.html
{% extends 'general.html' %}
{% load bootstrap4 %}
{% block titulo %}Modificar {{ alumno_registrado.nombre }} {{ alumno_registrado.apellido }}{% endblock titulo %}
{% block contenido %}

	<h1 class="text-white">Modificar {{ alumno_registrado.nombre }} {{ alumno_registrado.apellido }} </h1>

	<div class="card text-white bg-dark mb-3" style="padding: 15px">
	<form action="" method="post">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
    	<button type="submit" class="btn btn-success btn-lg btn-block">Modificar registro del alumno.</button>
    	<a href="{% url 'alumnos_mesas:detalle_alumno' alumno_registrado.id %}" class="btn btn-danger btn-lg btn-block" role="button">Volver</a>
		{% endbuttons %}
	</form>
	</div>
	
{% endblock contenido %}

templates/alumnos_mesas_examen/registrar_alumno.html
{% extends 'general.html' %}
{% load bootstrap4 %}
{% block titulo %}Registrar alumno{% endblock titulo %}
{% block contenido %}
	<h1 class="text-white">Registrar una alumno para mesa de examen:</h1>
	<div class="card text-white bg-dark mb-3" style="padding: 15px">
	<form action="" method="post">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
    	<button type="submit" class="btn btn-success btn-lg btn-block">Registrar alumno.</button>
    	<a href="{% url 'alumnos_mesas:listado_alumnos' %}" class="btn btn-danger btn-lg btn-block" role="button">Cancelar</a>
		{% endbuttons %}
	</form>
	</div>
{% endblock contenido %}

templates/general.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="static/css/styles.css">

  <title>Secretaría</title>

  <style>
    html, body {
      background-image: linear-gradient(#000000, #cccccc);

      background-size: 100%;
    }
  </style>

</head>
<body>
  <div style="min-height: 1000px;">
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand" href="{% url 'general' %}"><h1 class="h1" style="color: white;">Secretaría</h1></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'materia:listado' %}" style="color: white;">Materia</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'alumnos_mesas:listado_alumnos' %}" style="color: white;">Alumnos Registrados</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white;">
                {{ request.user.username|capfirst }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'logout'%}">Salir</a>
              </div>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login'%}" style="color: white;">Ingresar</a>
            </li>
          {% endif %}
        </ul>
      </div>
  </nav>
    <div class="contenido">
      <div class="container">
    {% block contenido %}
      <div class="row" style="margin-top: 5%">
        <div class="col-sm-6">
      	 <a href="{% url 'materia:listado' %}" class="btn btn-dark btn-lg btn-block" role="button" style="padding-top: 33%; padding-bottom: 33%;">Materias registradas</a>
        </div>
        <div class="col-sm-6">
      	 <a href="{% url 'alumnos_mesas:listado_alumnos' %}" class="btn btn-dark btn-lg btn-block" role="button" style="padding-top: 33%; padding-bottom: 33%;">Listado de alumnos registrados para mesa de examen</a>
        </div>
          <a href="{% url 'alumnos_mesas:formulario_alumno' %}" class="btn btn-dark btn-lg btn-block" role="button" style="padding-top: 5%; padding-bottom: 5%; margin-top: 30px; width:">Formulario para registro a mesa de examen</a>
      </div>
    {% endblock contenido %}
      </div>
    </div>
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/materia/borrar.html
{% extends 'general.html' %}
{% load bootstrap4 %}
{% block titulo %}Borrar: {{ materia.nombre }} {{ materia.año }}º {% endblock titulo %}
{% block contenido %}

	<h1 class="text-white">Borrar: {{ materia.nombre }} de {{ materia.año }}º </h1>
	<a href="{% url 'materia:detalle' materia.id %}" class="btn btn-danger btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Cancelar</a>
	<div class="card text-white bg-dark mb-3" style="padding: 15px">
	<form action="" method="post">
		{% csrf_token %}
		<p>Esta seguro que quiere borrar "{{ materia.nombre }} de {{ materia.año }}º"?</p>
		{% buttons %}
    	<button type="submit" class="btn btn-danger">Borrar materia.</button>
		{% endbuttons %}
	</form>
	</div>

{% endblock contenido %}

templates/materia/crear.html
{% extends 'general.html' %}
{% load bootstrap4 %}
{% block titulo %}Registrar materia{% endblock titulo %}
{% block contenido %}
	<h1 class="text-white">Registrar una materia:</h1>
	<a href="{% url 'materia:listado' %}" class="btn btn-danger btn-lg" role="button">Cancelar</a>
	<div class="card text-white bg-dark mb-3" style="padding: 15px">
	<form action="" method="post">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
    	<button type="submit" class="btn btn-success btn-lg btn-block">Registrar materia.</button>
		{% endbuttons %}
	</form>
	</div>
{% endblock contenido %}

templates/materia/detalle.html
{% extends 'general.html' %}
{% block titulo %} {{ materia.nombre }} {{ materia.año }}º {% endblock titulo %}
{% block contenido %}
	<h1 class="text-white">Detalles de la materia:</h1>
	<a href="{% url 'materia:listado' %}" class="btn btn-secondary btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Volver</a>
	<a href="{% url 'materia:modificar' materia.id %}" class="btn btn-secondary btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Modificar</a>
	<a href="{% url 'materia:borrar' materia.id %}" class="btn btn-danger btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;"z>Borrar</a>
	<div class="card text-white bg-dark mb-3" style="width: 100%;">
		<div class="card-header"><h5 class="card-title">{{ materia.nombre|capfirst }} de {{ materia.año }}º</h5></div>
		<div class="card-body">
			<p class="card-text">Fecha y hora a rendir: {{ materia.fecha_hora }}</p>
			<p class="card-text">Aula en la que se rendirá: {{ materia.aula }}</p>
		</div>
		<div class="card-footer">
			<p class="card-text">Profesores que evaluarán: {{ materia.profesores|capfirst }}</p>
		</div>
	</div>

{% endblock contenido %}

templates/materia/listado.html
{% extends 'general.html' %}
{% block titulo %}Materias{% endblock titulo %}
{% block contenido %}
<div class="container">
	<h1 class="text-white">Todas las materias registradas:</h1>
	<a href="{% url 'materia:crear' %}"><button type="button" class="btn btn-outline-light btn-lg btn-block">Registrar una materia</button></a>
	</br>
	<div class="row">

	{% for materia in materias %}
	
	<div class="col-sm-6">
	<div class="card text-white bg-dark mb-3" style="width: 100%;">
		<div class="card-header">
			<a href="{% url 'materia:detalle' materia.id %}" style="a:link {color: white}"><h5 class="card-title">{{ materia.nombre|capfirst }} de {{ materia.año }}º</h5></a>
		</div>
		<div class="card-body">
			<p class="card-text">Fecha y hora a rendir: {{ materia.fecha_hora }}</p>
			<p class="card-text">Aula en la que se rendirá: {{ materia.aula }}</p>
		</div>
		<div class="card-footer">
			<p class="card-text">Profesores que evaluarán: {{ materia.profesores|capfirst }}</p>
		</div>
	</div>
	</div>

	{% endfor %}

	</div>
	<a href="{% url 'general' %}" class="btn btn-danger btn-lg btn-block" role="button">Volver a la pagina principal</a>
</div>
{% endblock contenido %}

templates/materia/modificar.html
{% extends 'general.html' %}
{% load bootstrap4 %}
{% block titulo %}Modificar {{ materia.nombre }} {{ materia.año }}º {% endblock titulo %}
{% block contenido %}

	<h1 class="text-white">Modificar {{ materia.nombre }} de {{ materia.año }}º </h1>
	<a href="{% url 'materia:detalle' materia.id %}" class="btn btn-danger btn-lg" role="button" style="margin-right: 10px; margin-bottom: 10px;">Cancelar</a>
	<div class="card text-white bg-dark mb-3" style="padding: 15px">
	<form action="" method="post">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
    	<button type="submit" class="btn btn-success btn-lg btn-block">Modificar materia.</button>
		{% endbuttons %}
	</form>
	</div>
	
{% endblock contenido %}